# Although Docker Compose creates a default network for all projects,
# we will specifically create and use one, for clarity.
networks:
  etwebnet:

volumes:
  db-data:

services:
  etweb:
    build:
      context: .
      target: final
    networks:
      - etwebnet
    ports:
      - 18080:8080
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ExpenseTrackerDB
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=something
    ports:
      - 15432:5432
    networks:
      - etwebnet

  adminer:
    image: adminer:standalone
    ports:
      - 18081:8080
    networks:
      - etwebnet
    environment:
      - ADMINER_DEFAULT_SERVER=db
