apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: et-web-pvc
  labels:
    component: et-web
    part-of: expensetracker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
